feeds:
 - url: https://mirror.animetosho.org/feed/rss2?only_tor=1
   regexp: (((\[HorribleSubs\] (Sword Art Online - Alicization - War of Underworld|Boku no Hero Academia|Babylon|Ahiru no Sora|Black Clover|Darwin's Game|Koisuru Asteroid|Magia Record))).*(\[1080p\])|\[AnonimOT\] Star☆Twinkle Precure|\[Some-Stuffs\]_Pocket_Monsters_\(2019\).*\(1080p\)|\[Erai-raws\] Nanatsu no Taizai - Kamigami no Gekirin - [0-9]* \[1080p)

